TOERH/config/routes.rb
TOERH::Application.routes.draw do

  use_doorkeeper do
    skip_controllers :applications
  end
  scope module: "api" do
    constraints(:subdomain => 'api', defaults: {format: 'json'}) do
      namespace :v1 do
        get 'users/me' => 'users#me'
        resources :resources, :licenses, :resource_types, except: [:edit]
        resources :tags, :users,  only: [:index, :show]  
      end

      match '*path', via: :all, to: 'errors#error_404'
    end
  end

  scope module: "developers" do
    
    constraints(:subdomain => 'developers') do
      get '' => 'developers#index', :as => 'devs'

      get 'docs' => 'docs#index'
      get 'docs/other' => 'docs#other', :as => 'doc_other'
      get 'docs/auth' => 'docs#auth', :as => 'doc_auth'
      get 'docs/resources' => 'docs#resources', :as => 'doc_resources'
      get 'docs/rate-limit' => 'docs#rate_limit', :as => 'doc_rate_limit'
      get 'docs/limit-offset' => 'docs#limit_offset', :as => 'doc_limit_offset'

      

      namespace :admin do
        resources :applications, only: [:index, :edit, :update], :controller => "applications"
        get   '' => 'admins#index', :as => 'home'
      end

      resources :applications
    end
  end

  scope module: "users" do
    get   'register' => 'registrations#new', :as => 'register'
    post  'register' => 'registrations#create', :as => 'registerPost'
    get   'login' => 'authorizations#show', :as => 'login'
    post  'login' => 'authorizations#login', :as => 'loginPost'
    get   'logout' => 'authorizations#logout', :as => 'logout'
  end
  

  root 'home#index'

     

end

TOERH/app/controllers/developers/admin/admins_controller.rb
class Developers::Admin::AdminsController < ApplicationController
	before_action :require_login, :require_admin
	layout "developers"

	def index
		
	end


end

TOERH/app/controllers/developers/admin/applications_controller.rb
class Developers::Admin::ApplicationsController < ApplicationController
	before_action :require_login, :require_admin
	layout "developers"

	def index
		@applications = Doorkeeper::Application.all
	end

	def edit
		@application = Doorkeeper::Application.find_by_id(params[:id])
	end

	def update
		@application = Doorkeeper::Application.find_by_id(params[:id])

		if @application.update(application_params)
			if !@application.active
				REDIS.del(@application.uid)
			end
			redirect_to admin_applications_path(@application)
		else
			render 'edit'
		end
	end

	private
	
	def application_params
		params.require(:application).permit(:name, :redirect_uri, :active, :application_rate_limit_id)
	end
end

TOERH/app/controllers/developers/applications_controller.rb
class Developers::ApplicationsController < ApplicationController
	before_action :require_login
	layout "developers"

	def index
		@applications = current_user.oauth_applications
	end

	def show
		@application = current_user.oauth_applications.find(params[:id])
	end

	def new
		@application = Doorkeeper::Application.new
	end

	def create
		@application = Doorkeeper::Application.new(application_params)
		@application.owner = current_user
		@application.application_rate_limit = ApplicationRateLimit.order(limit: :asc).first

		if @application.save
			redirect_to application_path(@application)
		else
			render :new
		end
	end

	def edit
		@application = current_user.oauth_applications.find(params[:id])
	end

	def update
		@application = current_user.oauth_applications.find(params[:id])

		if @application.update(application_params)
			redirect_to application_path(@application)
		else
			render :edit
		end
	end

	def destroy
		@application = current_user.oauth_applications.find(params[:id])

		if @application.delete
			flash[:notice] = 'The application "' + @application.name + '"" has been deleted.'
			redirect_to applications_path
		else
			render :show, :alert => 'Error deleteing application.'
		end
	end

	private

	def application_params
		params.require(:application).permit(:name, :redirect_uri)
	end
end

TOERH/app/controllers/developers/developers_controller.rb
class Developers::DevelopersController < ApplicationController
	layout "developers"

	def index

	end
end

TOERH/app/controllers/developers/docs_controller.rb
class Developers::DocsController < ApplicationController
	layout "developers"
	
	def index

	end

	def auth

	end

	def users

	end

	def resources

	end

	def rate_limit
		
	end

	def limit_offset
		
	end
end

TOERH/app/controllers/developers/users/authorizations_controller.rb
class Developers::Users::AuthorizationsController < ApplicationController
	layout "developers"
	
	def show
		if !current_user.nil?
			redirect_to root_path
		end
	end

	def login
		user = User.find_by_email(params[:email])

		if user && user.authenticate(params[:password])
			session[:userid] = user.id
			redirect_to applications_path
		else
			@error = "Invalid E-mail and/or password."
			render :action => "show"
		end

	end

	def logout
		session[:userid] = nil
		flash[:notice] = "You have been logged out."
		redirect_to root_path
	end
	
end

TOERH/app/controllers/developers/users/registrations_controller.rb
class Developers::Users::RegistrationsController < ApplicationController
	layout "developers"

	def new
		if !current_user.nil?
			redirect_to root_path
		end
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			session[:userid] = @user.id
			redirect_to applications_path
		else
			render :action => 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
	end
end

TOERH/app/helpers/developers/admin/admins_helper.rb
module Developers::Admin::AdminsHelper
end

TOERH/app/helpers/developers/admin/applications_helper.rb
module Developers::Admin::ApplicationsHelper
end

TOERH/app/helpers/developers/applications_helper.rb
module Developers::ApplicationsHelper
end

TOERH/app/helpers/developers/developers_helper.rb
module Developers::DevelopersHelper
end

TOERH/app/helpers/developers/docs_helper.rb
module Developers::DocsHelper
end

TOERH/app/views/developers/docs/_menu.html.erb
<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
  <div class="list-group">
    <%= link_to "Getting Started", docs_path, :class => "list-group-item " + (current_page?(action: "index") ? "active" : "") %>
    <%= link_to "Auth", doc_auth_path, :class => "list-group-item " + (current_page?(action: "auth") ? "active" : "") %>   
    <%= link_to "Resources", doc_resources_path, :class => "list-group-item " + (current_page?(action: "resources") ? "active" : "") %>
    <%= link_to "Rate limiting", doc_rate_limit_path, :class => "list-group-item " + (current_page?(action: "rate_limit") ? "active" : "") %>
    <%= link_to "Limit and Offset", doc_limit_offset_path, :class => "list-group-item " + (current_page?(action: "limit_offset") ? "active" : "") %>
    <%= link_to "Other", doc_other_path, :class => "list-group-item " + (current_page?(action: "other") ? "active" : "") %>
  </div>
</div>
<!--/span-->

TOERH/app/views/developers/docs/auth.html.erb
<div class="row row-offcanvas row-offcanvas-left">
	<%= render "menu" %>
	<p class="pull-left visible-xs">
		<button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
	</p>
	<div class="col-xs-12 col-sm-9">
		<h1>Auth</h1>
		<div class="row">
			<div class="col-xs-12">
				<h3>Api Key</h3>
				<p>All request made to the Api requires a valid Api key. You can find the Api key on the application page for your application. The Api key should be put in the X-CLIENT-ID header. </p>
		

				<h3>User authenticating</h3>
				<p>Some request requires a valid user. To make a request to a protected resource you need to authenticate the user using oauth2.<br/>
				Put the returned token in the Authorization. <br/>
				header[Authorization] = Bearer 'Token'</p>
				<p>Doc not done</p>
			</div>
		</div>
	</div>
</div>

TOERH/app/views/developers/docs/index.html.erb
<div class="row row-offcanvas row-offcanvas-left">
	<%= render "menu" %>
	<p class="pull-left visible-xs">
		<button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
	</p>
	<div class="col-xs-12 col-sm-9">
		<h1>Getting Started</h1>
		<div class="row">
			<div class="col-xs-12">
				<h2>Applications</h2>
				To be able to make any requests to the Api you need to have a registred application.
				<% if current_user.nil? %>
				You need to be signed in to create a application.
				<%= link_to "Sign in", login_path %>
				or
				<%= link_to "sign up", register_path %>
				to get started.
				<% else %>
				<%= link_to "Create", new_application_path %>
				a application to get started.
				<% end %></div>
		</div>

		<div class="row">
			<div class="col-xs-12">
				<h2>Next steps</h2>
				<ul>
					<li>
						<%= link_to "How to authenticate requests?", doc_auth_path %></li>
					<li>
						<%= link_to "How is rate limiting managed?", doc_rate_limit_path %></li>
					<li>
						<%= link_to "How to get, create, update and delete resources (CRUD)", doc_resources_path %></li>
					<li>
						<%= link_to "How to paginate a response?", doc_limit_offset_path %></li>
				</ul>
			</div>
			<!--/row-->
		</div>
		<!--/span-->

	</div>
	<!--/row-->

TOERH/app/views/developers/docs/limit_offset.html.erb
<div class="row row-offcanvas row-offcanvas-left">
	<%= render "menu" %>
	<p class="pull-left visible-xs">
		<button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
	</p>
	<div class="col-xs-12 col-sm-9">

		<h1>Limit and offset</h1>
		<div class="row">
			<div class="col-xs-12">
				<ul>
					<li>
						Limit: Number of objects to return, between 1-30. Passing anything else will result in a limit of 30
					</li>
					<li>
						Offset: Number of objects to skip, between 0-x. Passing anything else will result in a offset of 0. Use this to paginate the result. Increase the offset with the limit for each new "page".
					</li>
				</ul>
				<h3>Example</h3>
				<p>
					GET: http://api.lvh.me:3000/v1/resources?api_key=YOUR_API_KEY&limit=10&offset=20
				</p>
			</div>
			<!--/span-->

			<!--/span-->
		</div>
		<!--/row-->
	</div>
	<!--/span-->

</div>
<!--/row-->

TOERH/app/views/developers/docs/other.html.erb
<div class="row row-offcanvas row-offcanvas-left">
	<%= render "menu" %>
	<p class="pull-left visible-xs">
		<button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
	</p>
	<div class="col-xs-12 col-sm-9">
		<h1>Other</h1>
		<div class="row">
			<div class="col-xs-12">
				<p>
					This page applies to the following end-points:
					<ul>
						<li>users</li>
						<li>tags</li>
						<li>resource_types</li>
						<li>licenses</li>
					</ul>
					For the urls, change "-end-point-" to any of the above
				</p>
			</div>
			<div class="col-xs-12">
				<h2>Get one</h2>
				<p>Returns the requested object.</p>
				<hr/>
				<h4>Requires a authenticated user</h4>
				<p>
					<span class="label label-warning">No</span>
				</p>
				<hr/>
				<h4>Url</h4>
				<p>GET: /-end-point-/:id</p>
				<hr/>
				<h4>Parameters</h4>
				<dl class="dl-horizontal">
					<dt>
						id
						<br/>
						<span class="label label-danger">required</span>
					</dt>
					<dd>
						<p>The full id of the desired object.</p>
						Example: f1bae8d5-d5ed-43e6-8247-69b9cbf32611
					</dd>
				</dl>
				<hr/>
				<h4>Limit and offset</h4>
				<p>
					<span class="label label-warning">No</span>
				</p>
			</div>
			<div class="col-xs-12">
				<h2>Get many</h2>
				<p>Returns 0-30 objects</p>
				<hr/>
				<h4>Requires a authenticated user</h4>
				<p>
					<span class="label label-warning">No</span>
				</p>
				<hr/>
				<h4>Url</h4>
				<p>GET: /-end-point-</p>
				<hr/>
				<h4>Parameters</h4>
				<dl class="dl-horizontal">
					<dt>q</br>
					<span class="label label-info">optional</span>
				</dt>
				<dd>
					<p>
						Search for only objects that have a name that contains the value of "q". For users the name equals firstname or lastname
					</p>
					Example: q=Karl
					<hr/>
				</dd>
			</dl>
			<hr/>
			<h4>Limit and offset</h4>
			<p>
				<span class="label label-success">Yes</span>
			</p>
		</div>
		<!--/span-->

		<!--/span-->
	</div>
	<!--/row-->
</div>
<!--/span-->

</div>
<!--/row-->

TOERH/app/views/developers/docs/rate_limit.html.erb
<div class="row row-offcanvas row-offcanvas-left">
	<%= render "menu" %>
	<p class="pull-left visible-xs">
		<button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
	</p>
	<div class="col-xs-12 col-sm-9">
		<h1>Rate limiting</h1>
		<div class="row">
			<div class="col-xs-12">
				<p>
					All request made to the Api are rate limited. All request is rate limited per hour. Depending on rate limit of the requesting application you can make x request per hour.
				</p>
				<p>
					Rate limiting is per application or per user. A request made with valid user credentials will not affect the current request count of the application, even if the request is made to a end-point that do not require a authenticated user.
				</p>

				<p>
					All users can make 5000 request per hour, this limit should almost be impossible to reach.
				</p>

				<h3>Headers</h3>
				<p>
					All successfull request will have 3 headers that contain information about the current rate limit.
				</p>
				<ul>
					<li>
						"X-Rate-Limit-Limit" => Total number of request possible per hour. Ex: 5000
					</li>
					<li>
						"X-Rate-Limit-Remaining" => Total number of request remaining for the current request time window. Ex: 4612
					</li>
					<li>
						"X-Rate-Limit-Reset" => The time when the current rate limit will reset, as number of seconds since the Epoch.
					</li>
				</ul>
			</div>
			<!--/span-->

			<!--/span-->
		</div>
		<!--/row-->
	</div>
	<!--/span-->

</div>
<!--/row-->

TOERH/app/views/developers/docs/resources.html.erb
<div class="row row-offcanvas row-offcanvas-left">
	<%= render "menu" %>
	<p class="pull-left visible-xs">
		<button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
	</p>
	<div class="col-xs-12 col-sm-9">
		<h1>Resources</h1>
		<div class="row">
			<div class="col-xs-12">
				<h2>Get Resource</h2>
				<p>Returns the requested resource.</p>
				<hr/>
				<h4>Requires a authenticated user</h4>
				<p>
					<span class="label label-warning">No</span>
				</p>
				<hr/>
				<h4>Url</h4>
				<p>GET: /resources/:id</p>
				<hr/>
				<h4>Parameters</h4>
				<dl class="dl-horizontal">
					<dt>
						id
						<br/>
						<span class="label label-danger">required</span>
					</dt>
					<dd>
						<p>The full id of the desired resource.</p>
						Example: f1bae8d5-d5ed-43e6-8247-69b9cbf32611
					</dd>
				</dl>
				<hr/>
				<h4>Limit and offset</h4>
				<p>
					<span class="label label-warning">No</span>
				</p>
			</div>
			<div class="col-xs-12">
				<h2>Get Resources</h2>
				<p>Returns 0-30 resources</p>
				<hr/>
				<h4>Requires a authenticated user</h4>
				<p>
					<span class="label label-warning">No</span>
				</p>
				<hr/>
				<h4>Url</h4>
				<p>GET: /resources</p>
				<hr/>
				<h4>Parameters</h4>
				<dl class="dl-horizontal">
					<dt>q</br>
					<span class="label label-info">optional</span>
				</dt>
				<dd>
					<p>
						Search for only resources that have a name that contains the value of "q"
					</p>
					Example: q=A github repo
					<hr/>
				</dd>

				<dt>resource_type_ids</br>
				<span class="label label-info">optional</span>
			</dt>
			<dd>
				<p>
					A comma (',') seperated list with the ids of the resource types to match to the resources.
				</p>
				Example: resource_type_ids=d4863faa-053f-49c6-9136-7177d31a6257, d4863faa-053f-49c6-9136-7177d31a6257
				<hr/>
			</dd>

			<dt>license_ids</br>
			<span class="label label-info">optional</span>
		</dt>
		<dd>
			<p>
				A comma (',') seperated list with the ids of the licenses to match to the resources.
			</p>
			Example: license_ids=d4863faa-053f-49c6-9136-7177d31a6257, d4863faa-053f-49c6-9136-7177d31a6257
			<hr/>
		</dd>

		<dt>user_ids</br>
		<span class="label label-info">optional</span>
	</dt>
	<dd>
		<p>
			A comma (',') seperated list with the ids of the users to match to the resources.
		</p>
		Example: user_ids=d4863faa-053f-49c6-9136-7177d31a6257
		<hr/>
	</dd>
	<dt>tags</br>
	<span class="label label-info">optional</span>
</dt>
<dd>
	<p>
		A comma (',') seperated list with the tags to match to the resources.
	</p>
	Example: tags=youtube, github
</dd>
</dl>
<hr/>
<h4>Limit and offset</h4>
<p>
<span class="label label-success">Yes</span>
</p>
<hr/>
<h4>Example</h4>
<p>
GET: <em>http://api.lvh.me:3000/v1/resources?api_key=YOUR_API_KEY</em>
</p>
<div class="well" ></div>
</div>

<div class="col-xs-12">
<h2>Create Resource</h2>
<p>Create a new resource. Returns the created resource.</p>
<hr/>
<h4>Requires a authenticated user</h4>
<p>
<span class="label label-success">Yes</span>
</p>
<hr/>
<h4>Url</h4>
<p>Post: /resources</p>
<hr/>
<h4>Post data</h4>
<dl class="dl-horizontal">
<dt>
	name
	<br/>
	<span class="label label-danger">required</span>
</dt>
<dd>
	The full name of the resource. Length: min: 5, max: 100
	<hr/>
</dd>
<dt>
	description
	<br/>
	<span class="label label-danger">required</span>
</dt>
<dd>
	The full description of the resource. Length: min: 10, max: 2000
	<hr/>
</dd>
<dt>
	url
	<br/>
	<span class="label label-danger">required</span>
</dt>
<dd>
	The full url of the resource. Length: min: 5, max: 200
	<hr/>
</dd>
<dt>
	resource_type_id
	<br/>
	<span class="label label-danger">required</span>
</dt>
<dd>
	A valid resource typ id.
	<hr/>
</dd>
<dt>
	license_id
	<br/>
	<span class="label label-danger">required</span>
</dt>
<dd>
	A valid license id
	<hr/>
</dd>
<dt>
	tags
	<br/>
	<span class="label label-info">optional</span>
</dt>
<dd>Array of tag names.</dd>
</dl>
<hr/>
<h4>Limit and offset</h4>
<p>
<span class="label label-warning">No</span>
</p>
<hr/>
</div>
<div class="col-xs-12">
<h2>Update Resource</h2>
<p>Update a resource. Returns the updated resource.</p>
<hr/>
<h4>Requires a authenticated user</h4>
<p>
<span class="label label-success">Yes</span>
</p>
<hr/>
<h4>Url</h4>
<p>PUT: /resources/:id</p>
<hr/>
<h4>Post data</h4>
<dl class="dl-horizontal">
<dt>
	id
	<br/>
	<span class="label label-danger">required</span>
</dt>
<dd>
	<p>The full id of the desired resource.</p>
	Example: f1bae8d5-d5ed-43e6-8247-69b9cbf32611
</dd>
<dt>
	name
	<br/>
	<span class="label label-info">optional</span>
</dt>
<dd>
	The full name of the resource. Length: min: 5, max: 100
	<hr/>
</dd>
<dt>
	description
	<br/>
	<span class="label label-info">optional</span>
</dt>
<dd>
	The full description of the resource. Length: min: 10, max: 2000
	<hr/>
</dd>
<dt>
	url
	<br/>
	<span class="label label-info">optional</span>
</dt>
<dd>
	The full url of the resource. Length: min: 5, max: 200
	<hr/>
</dd>
<dt>
	resource_type_id
	<br/>
	<span class="label label-info">optional</span>
</dt>
<dd>
	A valid resource typ id.
	<hr/>
</dd>
<dt>
	license_id
	<br/>
	<span class="label label-info">optional</span>
</dt>
<dd>
	A valid license id
	<hr/>
</dd>
<dt>
	tags
	<br/>
	<span class="label label-danger">required</span>
</dt>
<dd>Array of tags name. Will replace the old tags</dd>
</dl>
<hr/>
<h4>Limit and offset</h4>
<p>
<span class="label label-warning">No</span>
</p>
</div>
<div class="col-xs-12">
<h2>Delete Resource</h2>
<p>Delete a resource</p>
<hr/>
<h4>Requires a authenticated user</h4>
<p>
<span class="label label-success">Yes</span>
</p>
<hr/>
<h4>Url</h4>
<p>DELETE: /resources/:id</p>
<hr/>
<h4>Parameters</h4>
<dl class="dl-horizontal">
<dt>
	id
	<br/>
	<span class="label label-danger">required</span>
</dt>
<dd>
	<p>The full id of the desired resource.</p>
	Example: f1bae8d5-d5ed-43e6-8247-69b9cbf32611
</dd>
</dl>
<hr/>
<h4>Limit and offset</h4>
<p>
<span class="label label-warning">No</span>
</p>
</div>
</div>
</div>
</div>