TOERH/config/routes.rb
TOERH::Application.routes.draw do

  use_doorkeeper do
    skip_controllers :applications
  end
  scope module: "api" do
    constraints(:subdomain => 'api', defaults: {format: 'json'}) do
      namespace :v1 do
        get 'users/me' => 'users#me'
        resources :resources, :licenses, :resource_types, except: [:edit]
        resources :tags, :users,  only: [:index, :show]  
      end

      match '*path', via: :all, to: 'errors#error_404'
    end
  end

  scope module: "developers" do
    
    constraints(:subdomain => 'developers') do
      get '' => 'developers#index', :as => 'devs'

      get 'docs' => 'docs#index'
      get 'docs/other' => 'docs#other', :as => 'doc_other'
      get 'docs/auth' => 'docs#auth', :as => 'doc_auth'
      get 'docs/resources' => 'docs#resources', :as => 'doc_resources'
      get 'docs/rate-limit' => 'docs#rate_limit', :as => 'doc_rate_limit'
      get 'docs/limit-offset' => 'docs#limit_offset', :as => 'doc_limit_offset'

      

      namespace :admin do
        resources :applications, only: [:index, :edit, :update], :controller => "applications"
        get   '' => 'admins#index', :as => 'home'
      end

      resources :applications
    end
  end

  scope module: "users" do
    get   'register' => 'registrations#new', :as => 'register'
    post  'register' => 'registrations#create', :as => 'registerPost'
    get   'login' => 'authorizations#show', :as => 'login'
    post  'login' => 'authorizations#login', :as => 'loginPost'
    get   'logout' => 'authorizations#logout', :as => 'logout'
  end
  

  root 'home#index'

     

end

TOERH/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

TOERH/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TOERH', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Devs", devs_url %></li>
          <% if request.subdomain == 'developers' %>
            <li><%= link_to "Docs", docs_url %></li> 
          <% end %>        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

TOERH/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if current_user.nil? %>
	<li><%= link_to "Sign up", register_url(subdomain: false) %></li>
	<li><%= link_to "Sign in", login_url(subdomain: false) %></li>
<% else %>
	<% if current_user.is_admin %>
		<li><%= link_to "Admin", admin_home_url %></li>
	<% end %>
	<% if request.subdomain == 'developers' %>
		<li><%= link_to "My Apps", applications_url %></li>
	<% end %>	
	<li><%= link_to "Sign out", logout_url(subdomain: false) %></li>
<% end %>

TOERH/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Toerh" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Toerh" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>
  </body>
</html>

TOERH/app/views/layouts/developers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TOERH - <%= content_for?(:title) ? yield(:title) : "Developers" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Toerh" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </body>
</html>