TOERH/config/routes.rb
TOERH::Application.routes.draw do

  use_doorkeeper do
    skip_controllers :applications
  end
  scope module: "api" do
    constraints(:subdomain => 'api', defaults: {format: 'json'}) do
      namespace :v1 do
        get 'users/me' => 'users#me'
        resources :resources, :licenses, :resource_types, except: [:edit]
        resources :tags, :users,  only: [:index, :show]  
      end

      match '*path', via: :all, to: 'errors#error_404'
    end
  end

  scope module: "developers" do
    
    constraints(:subdomain => 'developers') do
      get '' => 'developers#index', :as => 'devs'

      get 'docs' => 'docs#index'
      get 'docs/other' => 'docs#other', :as => 'doc_other'
      get 'docs/auth' => 'docs#auth', :as => 'doc_auth'
      get 'docs/resources' => 'docs#resources', :as => 'doc_resources'
      get 'docs/rate-limit' => 'docs#rate_limit', :as => 'doc_rate_limit'
      get 'docs/limit-offset' => 'docs#limit_offset', :as => 'doc_limit_offset'

      

      namespace :admin do
        resources :applications, only: [:index, :edit, :update], :controller => "applications"
        get   '' => 'admins#index', :as => 'home'
      end

      resources :applications
    end
  end

  scope module: "users" do
    get   'register' => 'registrations#new', :as => 'register'
    post  'register' => 'registrations#create', :as => 'registerPost'
    get   'login' => 'authorizations#show', :as => 'login'
    post  'login' => 'authorizations#login', :as => 'loginPost'
    get   'logout' => 'authorizations#logout', :as => 'logout'
  end
  

  root 'home#index'

     

end

TOERH/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper

  private

  def require_login
  	if current_user.nil? then
      save_location
  		redirect_to login_path subdomain: false
  	end
  end

  def require_admin
    if !current_user.is_admin then
      redirect_to root_path
    end
  end

  def save_location loc
    session[:return_url] = loc || request.original_url if request.get?
  end

  def redirect_back
    redirect_to (session[:return_url] || root_path)
    session[:return_url] = nil
  end

end

TOERH/app/controllers/developers/admin/admins_controller.rb
class Developers::Admin::AdminsController < ApplicationController
	before_action :require_login, :require_admin
	layout "developers"

	def index
		
	end


end

TOERH/app/controllers/developers/admin/applications_controller.rb
class Developers::Admin::ApplicationsController < ApplicationController
	before_action :require_login, :require_admin
	layout "developers"

	def index
		@applications = Doorkeeper::Application.all
	end

	def edit
		@application = Doorkeeper::Application.find_by_id(params[:id])
	end

	def update
		@application = Doorkeeper::Application.find_by_id(params[:id])

		if @application.update(application_params)
			if !@application.active
				REDIS.del(@application.uid)
			end
			redirect_to admin_applications_path(@application)
		else
			render 'edit'
		end
	end

	private
	
	def application_params
		params.require(:application).permit(:name, :redirect_uri, :active, :application_rate_limit_id)
	end
end

TOERH/app/controllers/developers/applications_controller.rb
class Developers::ApplicationsController < ApplicationController
	before_action :require_login
	layout "developers"

	def index
		@applications = current_user.oauth_applications
	end

	def show
		@application = current_user.oauth_applications.find(params[:id])
	end

	def new
		@application = Doorkeeper::Application.new
	end

	def create
		@application = Doorkeeper::Application.new(application_params)
		@application.owner = current_user
		@application.application_rate_limit = ApplicationRateLimit.order(limit: :asc).first

		if @application.save
			redirect_to application_path(@application)
		else
			render :new
		end
	end

	def edit
		@application = current_user.oauth_applications.find(params[:id])
	end

	def update
		@application = current_user.oauth_applications.find(params[:id])

		if @application.update(application_params)
			redirect_to application_path(@application)
		else
			render :edit
		end
	end

	def destroy
		@application = current_user.oauth_applications.find(params[:id])

		if @application.delete
			flash[:notice] = 'The application "' + @application.name + '"" has been deleted.'
			redirect_to applications_path
		else
			render :show, :alert => 'Error deleteing application.'
		end
	end

	private

	def application_params
		params.require(:application).permit(:name, :redirect_uri)
	end
end

TOERH/app/controllers/developers/developers_controller.rb
class Developers::DevelopersController < ApplicationController
	layout "developers"

	def index

	end
end

TOERH/app/controllers/developers/docs_controller.rb
class Developers::DocsController < ApplicationController
	layout "developers"
	
	def index

	end

	def auth

	end

	def users

	end

	def resources

	end

	def rate_limit
		
	end

	def limit_offset
		
	end
end

TOERH/app/controllers/developers/users/authorizations_controller.rb
class Developers::Users::AuthorizationsController < ApplicationController
	layout "developers"
	
	def show
		if !current_user.nil?
			redirect_to root_path
		end
	end

	def login
		user = User.find_by_email(params[:email])

		if user && user.authenticate(params[:password])
			session[:userid] = user.id
			redirect_to applications_path
		else
			@error = "Invalid E-mail and/or password."
			render :action => "show"
		end

	end

	def logout
		session[:userid] = nil
		flash[:notice] = "You have been logged out."
		redirect_to root_path
	end
	
end

TOERH/app/controllers/developers/users/registrations_controller.rb
class Developers::Users::RegistrationsController < ApplicationController
	layout "developers"

	def new
		if !current_user.nil?
			redirect_to root_path
		end
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			session[:userid] = @user.id
			redirect_to applications_path
		else
			render :action => 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
	end
end

TOERH/app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

end

TOERH/app/helpers/developers/admin/admins_helper.rb
module Developers::Admin::AdminsHelper
end

TOERH/app/helpers/developers/admin/applications_helper.rb
module Developers::Admin::ApplicationsHelper
end

TOERH/app/helpers/developers/applications_helper.rb
module Developers::ApplicationsHelper
end

TOERH/app/helpers/developers/developers_helper.rb
module Developers::DevelopersHelper
end

TOERH/app/helpers/developers/docs_helper.rb
module Developers::DocsHelper
end

TOERH/app/views/developers/applications/_form.html.erb
<div class="row">
	<div class="col-xs-12">

		<%= form_for application, role: 'form' do |f| %>

			<fieldset>
				<legend><%= (application.id? ? 'Edit' : 'Create') %> application</legend>

				<% if application.errors.any? %>
		          <div class="alert alert-warning">
		            <h4>Input errors</h4>

		            <ul>
		              <% application.errors.full_messages.each do |msg| %>
		                <li><%= msg %></li>
		              <% end %>
		            </ul>
		          </div>

		        <% end %>

				<div class="form-group">
					<%= f.label(:name) %>
					<%= f.text_field(:name, :class => 'form-control') %>
				</div>

				<div class="form-group">
					<%= f.label(:redirect_uri) %>
					<%= f.text_field(:redirect_uri, :class => 'form-control') %>
				</div>

				<p>
					<%= f.submit (application.id? ? 'Save' : 'Create'), :class => "btn btn-primary btn-sm" %>
					<%= link_to "Cancel", (application.id? ? application_path(application) : applications_path), :class => "btn btn-warning btn-sm" %>
				</p>
			</fieldset>

		<% end %>

		

	</div>
</div>

TOERH/app/views/developers/applications/edit.html.erb
<%= render partial: "form", locals: {application: @application} %>

TOERH/app/views/developers/applications/index.html.erb
<div class="row">
	<div class="col-xs-12">
		<h1>My Apps</h1>
		<div class="row">
			<div class="col-xs-12">
				<%= link_to "New Application", new_application_path, class: 'btn btn-primary btn-sm' %>
			</div>
		</div>
		<% if @applications.any? %>
		<div class="row">
			<div class="col-xs-12">
			<table class="table">
				<thead>
					<tr>
						<th>Name</th>
						<th>Created</th>
						<th>Status</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @applications.each do |app| %>
					<tr>
						<td>
							<%= app.name %></td>
						<td>
							<%= app.created_at.strftime("%Y-%m-%d") %></td>
						<td>
								<%= (app.active ? "Active" : "Revoked") %></td>
						<td>
							<%= link_to 'Details', application_path(app), :class => 'btn btn-info btn-xs' %></td>
					</tr>
					<% end %></tbody>
			</table>
			</div>
		</div>
		
		<% else %>
			<div class="row col-xs-12">You have not created any applications.</div>
		<% end %></div>
</div>

TOERH/app/views/developers/applications/new.html.erb
<%= render partial: "form", locals: {application: @application} %>

TOERH/app/views/developers/applications/show.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1>
            App: <%= @application.name %>
        </h1>
        
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="col-xs-10">            
                
                    <h5><strong>Api Key:</strong></h5>
                    <p>
                        <%= @application.uid %>
                    </p>

                    <h5><strong>Api secret:</strong></h5>
                    <p>
                        <%= @application.secret %>
                    </p>

                    <h5><strong>Redirect uri:</strong></h5>
                    <p>
                        <%= @application.redirect_uri %>
                    </p>

                    <h5><strong>Rate limit:</strong></h5>
                    <p>
                        <%= @application.application_rate_limit.name %>, <%= @application.application_rate_limit.limit %>
                    </p>

                    <h5><strong>Status:</strong></h5>
                    <p>
                        <%= (@application.active ? "Active" : "Revoked") %>
                    </p>

                    <h5><strong>Created:</strong></h5>
                    <p>
                        <%= @application.created_at.strftime("%Y-%m-%d") %>
                    </p>

                    <h5><strong>Updated:</strong></h5>
                    <p>
                        <%= @application.updated_at.strftime("%Y-%m-%d") %>
                    </p>

                    <p>
                        <%= link_to 'Back to application list', applications_path %>
                    </p>
                </div>
                <div class="col-xs-2">         
                    <%= link_to 'Edit', edit_application_path(@application), :class => 'pull-right btn btn-primary btn-sm' %>
                    
                    <span class="clearfix" ></span>
                    <br/>

                    <%= form_for @application, method: 'delete'  do |f| %>
                        <%= f.submit 'Delete', :class => "pull-right btn btn-danger btn-sm", :onclick => 'return confirm("Delete this application? This CANNOT be undone!")' %>
                    <% end %>

                </div>
            </div> 
        </div>


        <p>
            
        </p>
    </div>
</div>