TOERH/config/routes.rb
TOERH::Application.routes.draw do

  use_doorkeeper do
    skip_controllers :applications
  end
  scope module: "api" do
    constraints(:subdomain => 'api', defaults: {format: 'json'}) do
      namespace :v1 do
        get 'users/me' => 'users#me'
        resources :resources, :licenses, :resource_types, except: [:edit]
        resources :tags, :users,  only: [:index, :show]  
      end

      match '*path', via: :all, to: 'errors#error_404'
    end
  end

  scope module: "developers" do
    
    constraints(:subdomain => 'developers') do
      get '' => 'developers#index', :as => 'devs'

      get 'docs' => 'docs#index'
      get 'docs/other' => 'docs#other', :as => 'doc_other'
      get 'docs/auth' => 'docs#auth', :as => 'doc_auth'
      get 'docs/resources' => 'docs#resources', :as => 'doc_resources'
      get 'docs/rate-limit' => 'docs#rate_limit', :as => 'doc_rate_limit'
      get 'docs/limit-offset' => 'docs#limit_offset', :as => 'doc_limit_offset'

      

      namespace :admin do
        resources :applications, only: [:index, :edit, :update], :controller => "applications"
        get   '' => 'admins#index', :as => 'home'
      end

      resources :applications
    end
  end

  scope module: "users" do
    get   'register' => 'registrations#new', :as => 'register'
    post  'register' => 'registrations#create', :as => 'registerPost'
    get   'login' => 'authorizations#show', :as => 'login'
    post  'login' => 'authorizations#login', :as => 'loginPost'
    get   'logout' => 'authorizations#logout', :as => 'logout'
  end
  

  root 'home#index'

     

end

TOERH/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper

  private

  def require_login
  	if current_user.nil? then
      save_location
  		redirect_to login_path subdomain: false
  	end
  end

  def require_admin
    if !current_user.is_admin then
      redirect_to root_path
    end
  end

  def save_location loc
    session[:return_url] = loc || request.original_url if request.get?
  end

  def redirect_back
    redirect_to (session[:return_url] || root_path)
    session[:return_url] = nil
  end

end

TOERH/app/controllers/developers/admin/applications_controller.rb
class Developers::Admin::ApplicationsController < ApplicationController
	before_action :require_login, :require_admin
	layout "developers"

	def index
		@applications = Doorkeeper::Application.all
	end

	def edit
		@application = Doorkeeper::Application.find_by_id(params[:id])
	end

	def update
		@application = Doorkeeper::Application.find_by_id(params[:id])

		if @application.update(application_params)
			if !@application.active
				REDIS.del(@application.uid)
			end
			redirect_to admin_applications_path(@application)
		else
			render 'edit'
		end
	end

	private
	
	def application_params
		params.require(:application).permit(:name, :redirect_uri, :active, :application_rate_limit_id)
	end
end

TOERH/app/controllers/developers/applications_controller.rb
class Developers::ApplicationsController < ApplicationController
	before_action :require_login
	layout "developers"

	def index
		@applications = current_user.oauth_applications
	end

	def show
		@application = current_user.oauth_applications.find(params[:id])
	end

	def new
		@application = Doorkeeper::Application.new
	end

	def create
		@application = Doorkeeper::Application.new(application_params)
		@application.owner = current_user
		@application.application_rate_limit = ApplicationRateLimit.order(limit: :asc).first

		if @application.save
			redirect_to application_path(@application)
		else
			render :new
		end
	end

	def edit
		@application = current_user.oauth_applications.find(params[:id])
	end

	def update
		@application = current_user.oauth_applications.find(params[:id])

		if @application.update(application_params)
			redirect_to application_path(@application)
		else
			render :edit
		end
	end

	def destroy
		@application = current_user.oauth_applications.find(params[:id])

		if @application.delete
			flash[:notice] = 'The application "' + @application.name + '"" has been deleted.'
			redirect_to applications_path
		else
			render :show, :alert => 'Error deleteing application.'
		end
	end

	private

	def application_params
		params.require(:application).permit(:name, :redirect_uri)
	end
end

TOERH/app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

end

TOERH/app/helpers/developers/admin/applications_helper.rb
module Developers::Admin::ApplicationsHelper
end

TOERH/app/helpers/developers/applications_helper.rb
module Developers::ApplicationsHelper
end

TOERH/app/views/developers/admin/applications/edit.html.erb
<div class="row">
	<div class="col-xs-12">

		<%= form_for @application, url: {action: 'update'}, role: 'form' do |f| %>

		<fieldset>
			<legend>
				Edit:
				<%= @application.name %></legend>

			<% if @application.errors.any? %>
			<div class="alert alert-warning">
				<h4>Input errors</h4>

				<ul>
					<% @application.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %></li>
					<% end %></ul>
			</div>

			<% end %>

			<h5>Owner:</h5>
			<p>
				<%= @application.owner.firstname %>
				<%= @application.owner.lastname %></p>

			<h5>Api key:</h5>
            <p>
                <%= @application.uid %>
            </p>

			<h5>Api secret:</h5>
            <p>
                <%= @application.secret %>
            </p>

			<h5>Created:
			</h5>
			<p>
				<%= @application.created_at.strftime("%Y-%m-%d") %></p>

			<h5>Updated:
			</h5>
			<p>
				<%= @application.updated_at.strftime("%Y-%m-%d") %></p>

			<div class="form-group">
				<%= f.label(:name) %>
				<%= f.text_field(:name, :class =>'form-control') %></div>

			<div class="form-group">
				<%= f.label(:active, "Status") %>
				<%= f.select(:active, options_for_select([['Active', true], ['Revoked', false]], @application.active), {}, :class =>"form-control") %></div>

			<div class="form-group">
				<%= f.label(:application_rate_limit_id, "Rate Limit") %>
				<%= f.select(:application_rate_limit_id, 
						options_from_collection_for_select(ApplicationRateLimit.all, :id, :rate_limit_name_and_limit, @application.application_rate_limit_id), {}, :class =>
				"form-control") 
					%>
			</div>

			<p>
				<%= f.submit 'Save', :class =>
				"btn btn-primary btn-sm" %>
				<%= link_to "Cancel", admin_applications_path, :class =>"btn btn-warning btn-sm" %></p>
		</fieldset>

		<% end %></div>
</div>

TOERH/app/views/developers/admin/applications/index.html.erb
<div class="row">
	<div class="col-xs-12">
		<h1>All Apps</h1>
		<% if @applications.any? %>
		<div class="row">
			<div class="col-xs-12">
				<table class="table">
					<thead>
						<tr>
							<th>Name</th>
							<th>Created</th>
							<th>Owner</th>
							<th>Status</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @applications.each do |app| %>
						<tr>
							<td>
								<%= app.name %></td>
							<td>
								<%= app.created_at.strftime("%Y-%m-%d") %></td>
							<td>
								<%= app.owner.firstname %>
								<%= app.owner.lastname %></td>
							<td>
								<%= (app.active ? "Active" : "Revoked") %></td>
							<td>
								<%= link_to 'Details', edit_admin_application_path(app), :class =>'btn btn-info btn-xs' %></td>
						</tr>
						<% end %></tbody>
				</table>
			</div>
		</div>

		<% else %>
		<div class="row col-xs-12">No apps</div>
		<% end %></div>
</div>